server:
  port: 8080
spring:
  application:
    name: payments
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

# DataSource configuration
datasource:
  jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  type: com.zaxxer.hikari.HikariDataSource
  username: sa
  password: sa

# Monitoring endpoints
management:
  endpoints.web.exposure.include: "info, health, metrics, configprops, env"

listener:
  url: http://localhost:8081/notify
